VOICENAMES = {
    "ENGLISH": {'male': 'en-AU-WilliamNeural', 'female': 'en-AU-NatashaNeural'},
    "SPANISH": {'male': 'es-AR-TomasNeural', 'female': 'es-AR-ElenaNeural'},
    "FRENCH": {'male': 'fr-CA-AntoineNeural', 'female': 'fr-CA-SylvieNeural'},
    "ARABIC": {'male': 'ar-AE-HamdanNeural', 'female': 'ar-AE-FatimaNeural'},
    "GERMAN": {'male': 'de-DE-ConradNeural', 'female': 'de-DE-KatjaNeural'},
    "POLISH": {'male': 'pl-PL-MarekNeural', 'female': 'pl-PL-ZofiaNeural'},
    "ITALIAN": {'male': 'it-IT-DiegoNeural', 'female': 'it-IT-ElsaNeural'},
    "PORTUGUESE": {'male': 'pt-BR-AntonioNeural', 'female': 'pt-BR-FranciscaNeural'},
    "AFRIKAANS": {'male': 'af-ZA-WillemNeural', 'female': 'af-ZA-AdriNeural'},
    "AMHARIC": {'male': 'am-ET-AmehaNeural', 'female': 'am-ET-MekdesNeural'},
    "AZERBAIJANI": {'male': 'az-AZ-BabekNeural', 'female': 'az-AZ-BanuNeural'},
    "BULGARIAN": {'male': 'bg-BG-BorislavNeural', 'female': 'bg-BG-KalinaNeural'},
    "BENGALI": {'male': 'bn-BD-PradeepNeural', 'female': 'bn-BD-NabanitaNeural'},
    "BOSNIAN": {'male': 'bs-BA-GoranNeural', 'female': 'bs-BA-VesnaNeural'},
    "CATALAN": {'male': 'ca-ES-EnricNeural', 'female': 'ca-ES-JoanaNeural'},
    "CZECH": {'male': 'cs-CZ-AntoninNeural', 'female': 'cs-CZ-VlastaNeural'},
    "WELSH": {'male': 'cy-GB-AledNeural', 'female': 'cy-GB-NiaNeural'},
    "DANISH": {'male': 'da-DK-JeppeNeural', 'female': 'da-DK-ChristelNeural'},
    "GREEK": {'male': 'el-GR-NestorasNeural', 'female': 'el-GR-AthinaNeural'},
    "ESTONIAN": {'male': 'et-EE-KertNeural', 'female': 'et-EE-AnuNeural'},
    "PERSIAN": {'male': 'fa-IR-FaridNeural', 'female': 'fa-IR-DilaraNeural'},
    "FINNISH": {'male': 'fi-FI-HarriNeural', 'female': 'fi-FI-NooraNeural'},
    "FILIPINO": {'male': 'fil-PH-AngeloNeural', 'female': 'fil-PH-BlessicaNeural'},
    "GALICIAN": {'male': 'gl-ES-RoiNeural', 'female': 'gl-ES-SabelaNeural'},
    "GUJARATI": {'male': 'gu-IN-NiranjanNeural', 'female': 'gu-IN-DhwaniNeural'},
    "HEBREW": {'male': 'he-IL-AvriNeural', 'female': 'he-IL-HilaNeural'},
    "HINDI": {'male': 'hi-IN-MadhurNeural', 'female': 'hi-IN-SwaraNeural'},
    "CROATIAN": {'male': 'hr-HR-SreckoNeural', 'female': 'hr-HR-GabrijelaNeural'},
    "HUNGARIAN": {'male': 'hu-HU-TamasNeural', 'female': 'hu-HU-NoemiNeural'},
    "INDONESIAN": {'male': 'id-ID-ArdiNeural', 'female': 'id-ID-GadisNeural'},
    "ICELANDIC": {'male': 'is-IS-GunnarNeural', 'female': 'is-IS-GudrunNeural'},
    "ITALIAN": {'male': 'it-IT-DiegoNeural', 'female': 'it-IT-ElsaNeural'},
    "JAPANESE": {'male': 'ja-JP-KeitaNeural', 'female': 'ja-JP-NanamiNeural'},
    "JAVANESE": {'male': 'jv-ID-DimasNeural', 'female': 'jv-ID-SitiNeural'},
    "GEORGIAN": {'male': 'ka-GE-GiorgiNeural', 'female': 'ka-GE-EkaNeural'},
    "KAZAKH": {'male': 'kk-KZ-DauletNeural', 'female': 'kk-KZ-AigulNeural'},
    "KHMER": {'male': 'km-KH-PisethNeural', 'female': 'km-KH-SreymomNeural'},
    "KANNADA": {'male': 'kn-IN-GaganNeural', 'female': 'kn-IN-SapnaNeural'},
    "KOREAN": {'male': 'ko-KR-InJoonNeural', 'female': 'ko-KR-SunHiNeural'},
    "LAO": {'male': 'lo-LA-KeomanyNeural', 'female': 'lo-LA-ChanthavongNeural'},
    "LITHUANIAN": {'male': 'lt-LT-LeonasNeural', 'female': 'lt-LT-OnaNeural'},
    "LATVIAN": {'male': 'lv-LV-NilsNeural', 'female': 'lv-LV-EveritaNeural'},
    "MACEDONIAN": {'male': 'mk-MK-AleksandarNeural', 'female': 'mk-MK-MarijaNeural'},
    "MALAYALAM": {'male': 'ml-IN-MidhunNeural', 'female': 'ml-IN-MidhunNeural'},
    "MONGOLIAN": {'male': 'mn-MN-YesuiNeural', 'female': 'mn-MN-BataaNeural'},
    "MARATHI": {'male': 'mr-IN-ManoharNeural', 'female': 'mr-IN-AarohiNeural'},
    "MALAY": {'male': 'ms-MY-OsmanNeural', 'female': 'ms-MY-YasminNeural'},
    "MALTESE": {'male': 'mt-MT-JosephNeural', 'female': 'mt-MT-GraceNeural'},
    "MYANMAR": {'male': 'my-MM-ThihaNeural', 'female': 'my-MM-NilarNeural'},
    "NORWEGIAN": {'male': 'nb-NO-FinnNeural', 'female': 'nb-NO-PernilleNeural'},
    "NEPALI": {'male': 'ne-NP-SagarNeural', 'female': 'ne-NP-HemkalaNeural'},
    "DUTCH": {'male': 'nl-NL-MaartenNeural', 'female': 'nl-NL-FennaNeural'},
    "NORWEGIAN_BOKMAL": {'male': 'nb-NO-FinnNeural', 'female': 'nb-NO-PernilleNeural'},
    "NORWEGIAN_NYNORSK": {'male': 'nb-NO-FinnNeural', 'female': 'nb-NO-PernilleNeural'},
    "PASHTO": {'male': 'ps-AF-LatifaNeural', 'female': 'ps-AF-GulNawazNeural'},
    "ROMANIAN": {'male': 'ro-RO-EmilNeural', 'female': 'ro-RO-AlinaNeural'},
    "RUSSIAN": {'male': 'ru-RU-DmitryNeural', 'female': 'ru-RU-SvetlanaNeural'},
    "SINHALA": {'male': 'si-LK-SameeraNeural', 'female': 'si-LK-ThiliniNeural'},
    "SLOVAK": {'male': 'sk-SK-LukasNeural', 'female': 'sk-SK-ViktoriaNeural'},
    "SLOVENIAN": {'male': 'sl-SI-RokNeural', 'female': 'sl-SI-PetraNeural'},
    "SOMALI": {'male': 'so-SO-MuuseNeural', 'female': 'so-SO-UbaxNeural'},
    "ALBANIAN": {'male': 'sq-AL-IlirNeural', 'female': 'sq-AL-AnilaNeural'},
    "SERBIAN": {'male': 'sr-RS-NicholasNeural', 'female': 'sr-RS-SophieNeural'},
    "SUNDANESE": {'male': 'su-ID-JajangNeural', 'female': 'su-ID-TutiNeural'},
    "SWEDISH": {'male': 'sv-SE-MattiasNeural', 'female': 'sv-SE-SofieNeural'},
    "SWAHILI": {'male': 'sw-TZ-DaudiNeural', 'female': 'sw-TZ-DaudiNeural'},
    "TAMIL": {'male': 'ta-IN-ValluvarNeural', 'female': 'ta-IN-PallaviNeural'},
    "TELUGU": {'male': 'te-IN-MohanNeural', 'female': 'te-IN-ShrutiNeural'},
    "THAI": {'male': 'th-TH-NiwatNeural', 'female': 'th-TH-PremwadeeNeural'},
    "TURKISH": {'male': 'tr-TR-AhmetNeural', 'female': 'tr-TR-EmelNeural'},
    "UKRAINIAN": {'male': 'uk-UA-OstapNeural', 'female': 'uk-UA-PolinaNeural'},
    "URDU": {'male': 'ur-PK-AsadNeural', 'female': 'ur-PK-UzmaNeural'},
    "UZBEK": {'male': 'uz-UZ-SardorNeural', 'female': 'uz-UZ-MadinaNeural'},
    "VIETNAMESE": {'male': 'vi-VN-NamMinhNeural', 'female': 'vi-VN-HoaiMyNeural'},
    "CHINESE": {'male': 'zh-CN-YunxiNeural', 'female': 'zh-CN-XiaoxiaoNeural'},
    "ZULU": {'male': 'zu-ZA-ThembaNeural', 'female': 'zu-ZA-ThandoNeural'},
}
headers = {
"President's Secretariat" : "./assets/headers/President's Secretariat.png",
"Vice President's Secretariat" : "./assets/headers/Vice President's Secretariat.png",
"Prime Minister's Office" : "./assets/headers/Prime Minister's Office.png",
"Cabinet" : "./assets/headers/Cabinet.png",
"Cabinet Committee Decisions" : "./assets/headers/Cabinet Committee Decisions.png",
"Cabinet Committee on Economic Affairs (CCEA)" : "./assets/headers/Cabinet Committee on Economic Affairs (CCEA).png",
"Cabinet Secretariat" : "./assets/headers/Cabinet Secretariat.png",
"Cabinet Committee on Infrastructure" : "./assets/headers/Cabinet Committee on Infrastructure.png",
"Cabinet Committee on Price" : "./assets/headers/Cabinet Committee on Price.png",
"Cabinet Committee on Investment" : "./assets/headers/Cabinet Committee on Investment.png",
"AYUSH" : "./assets/headers/AYUSH.png",
"Other Cabinet Committees" : "./assets/headers/Other Cabinet Committees.png",
"Department of Space" : "./assets/headers/Department of Space.png",
"Department of Ocean Development" : "./assets/headers/Department of Ocean Development.png",
"Department of Atomic Energy" : "./assets/headers/Department of Atomic Energy.png",
"Election Commission" : "./assets/headers/Election Commission.png",
"Finance Commission" : "./assets/headers/Finance Commission.png",
"Ministry of Agriculture & Farmers Welfare" : "./assets/headers/Ministry of Agriculture & Farmers Welfare.png",
"Ministry of Agro & Rural Industries" : "./assets/headers/Ministry of Agro & Rural Industries.png",
"Ministry of Chemicals and Fertilizers" : "./assets/headers/Ministry of Chemicals and Fertilizers.png",
"Ministry of Civil Aviation" : "./assets/headers/Ministry of Civil Aviation.png",
"Ministry of Coal" : "./assets/headers/Ministry of Coal.png",
"Ministry of Commerce & Industry" : "./assets/headers/Ministry of Commerce & Industry.png",
"Ministry of Communications" : "./assets/headers/Ministry of Communications.png",
"Ministry of Company Affairs" : "./assets/headers/Ministry of Company Affairs.png",
"Ministry of Consumer Affairs, Food & Public Distribution" : "./assets/headers/Ministry of Consumer Affairs, Food & Public Distribution.png",
"Ministry of Cooperation" : "./assets/headers/Ministry of Cooperation.png",
"Ministry of Corporate Affairs" : "./assets/headers/Ministry of Corporate Affairs.png",
"Ministry of Culture" : "./assets/headers/Ministry of Culture.png",
"Ministry of Defence" : "./assets/headers/Ministry of Defence.png",
"Ministry of Development of North-East Region" : "./assets/headers/Ministry of Development of North-East Region.png",
"Ministry of Disinvestment" : "./assets/headers/Ministry of Disinvestment.png",
"Ministry of Drinking Water & Sanitation" : "./assets/headers/Ministry of Drinking Water & Sanitation.png",
"Ministry of Earth Sciences" : "./assets/headers/Ministry of Earth Sciences.png",
"Ministry of Education" : "./assets/headers/Ministry of Education.png",
"Ministry of Electronics & IT" : "./assets/headers/Ministry of Electronics & IT.png",
"Ministry of Environment, Forest and Climate Change" : "./assets/headers/Ministry of Environment, Forest and Climate Change.png",
"Ministry of External Affairs" : "./assets/headers/Ministry of External Affairs.png",
"Ministry of Finance" : "./assets/headers/Ministry of Finance.png",
"Ministry of Fisheries, Animal Husbandry & Dairying" : "./assets/headers/Ministry of Fisheries, Animal Husbandry & Dairying.png",
"Ministry of Food Processing Industries" : "./assets/headers/Ministry of Food Processing Industries.png",
"Ministry of Health and Family Welfare" : "./assets/headers/Ministry of Health and Family Welfare.png",
"Ministry of Heavy Industries" : "./assets/headers/Ministry of Heavy Industries.png",
"Ministry of Home Affairs" : "./assets/headers/Ministry of Home Affairs.png",
"Ministry of Housing & Urban Affairs" : "./assets/headers/Ministry of Housing & Urban Affairs.png",
"Ministry of Information & Broadcasting" : "./assets/headers/Ministry of Information & Broadcasting.png",
"Ministry of Jal Shakti" : "./assets/headers/Ministry of Jal Shakti.png",
"Ministry of Labour & Employment" : "./assets/headers/Ministry of Labour & Employment.png",
"Ministry of Law and Justice" : "./assets/headers/Ministry of Law and Justice.png",
"Ministry of Micro, Small & Medium Enterprises" : "./assets/headers/Ministry of Micro, Small & Medium Enterprises.png",
"Ministry of Mines" : "./assets/headers/Ministry of Mines.png",
"Ministry of Minority Affairs" : "./assets/headers/Ministry of Minority Affairs.png",
"Ministry of New and Renewable Energy" : "./assets/headers/Ministry of New and Renewable Energy.png",
"Ministry of Overseas Indian Affairs" : "./assets/headers/Ministry of Overseas Indian Affairs.png",
"Ministry of Panchayati Raj" : "./assets/headers/Ministry of Panchayati Raj.png",
"Ministry of Parliamentary Affairs" : "./assets/headers/Ministry of Parliamentary Affairs.png",
"Ministry of Personnel, Public Grievances & Pensions" : "./assets/headers/Ministry of Personnel, Public Grievances & Pensions.png",
"Ministry of Petroleum & Natural Gas" : "./assets/headers/Ministry of Petroleum & Natural Gas.png",
"Ministry of Planning" : "./assets/headers/Ministry of Planning.png",
"Ministry of Power" : "./assets/headers/Ministry of Power.png",
"Ministry of Railways" : "./assets/headers/Ministry of Railways.png",
"Ministry of Road Transport & Highways" : "./assets/headers/Ministry of Road Transport & Highways.png",
"Ministry of Rural Development" : "./assets/headers/Ministry of Rural Development.png",
"Ministry of Science & Technology" : "./assets/headers/Ministry of Science & Technology.png",
"Ministry of Ports, Shipping and Waterways" : "./assets/headers/Ministry of Ports, Shipping and Waterways.png",
"Ministry of Skill Development and Entrepreneurship" : "./assets/headers/Ministry of Skill Development and Entrepreneurship.png",
"Ministry of Social Justice & Empowerment" : "./assets/headers/Ministry of Social Justice & Empowerment.png",
"Ministry of Statistics & Programme Implementation" : "./assets/headers/Ministry of Statistics & Programme Implementation.png",
"Ministry of Steel" : "./assets/headers/Ministry of Steel.png",
"Ministry of Surface Transport" : "./assets/headers/Ministry of Surface Transport.png",
"Ministry of Textiles" : "./assets/headers/Ministry of Textiles.png",
"Ministry of Tourism" : "./assets/headers/Ministry of Tourism.png",
"Ministry of Tribal Affairs" : "./assets/headers/Ministry of Tribal Affairs.png",
"Ministry of Urban Development" : "./assets/headers/Ministry of Urban Development.png",
"Ministry of Water Resources, River Development and Ganga Rejuvenation" : "./assets/headers/Ministry of Water Resources, River Development and Ganga Rejuvenation.png",
"Ministry of Women and Child Development" : "./assets/headers/Ministry of Women and Child Development.png",
"Ministry of Youth Affairs and Sports" : "./assets/headers/Ministry of Youth Affairs and Sports.png",
"NITI Aayog" : "./assets/headers/NITI Aayog.png",
"PM Speech" : "./assets/headers/PM Speech.png",
"EAC-PM" : "./assets/headers/EAC-PM.png",
"UPSC" : "./assets/headers/UPSC.png",
"Special Service and Features" : "./assets/headers/Special Service and Features.png",
"PIB Headquarters" : "./assets/headers/PIB Headquarters.png",
"Office of Principal Scientific Advisor to GoI" : "./assets/headers/Office of Principal Scientific Advisor to GoI.png",
"National Financial Reporting Authority" : "./assets/headers/National Financial Reporting Authority.png",
"Competition Commission of India" : "./assets/headers/Competition Commission of India.png",
"IFSC Authority" : "./assets/headers/IFSC Authority.png",
"National Security Council Secretariat" : "./assets/headers/National Security Council Secretariat.png",
}